nombre= input('ingrese su nombre')
numerodecomision= input('ingrese su numero de comision')
asignatura= input('ingrese nombre de asignatura')
docente= input('ingrese nombre del docente')
asistencia=input('ingrese asistencia')
print('\n--- Datos ingresados ---')
print('Nombre', nombre)
print('Numero de comision', numerodecomision)
print('Asignatura',asignatura)
print('Docente',docente)
print('Asistencia',asistencia)